name: Continuous Integration
on:
  workflow_dispatch:
jobs:
  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            make

      - name: Check for make
        run : |
          ls /usr/bin | grep "make"
